import { NextResponse } from "next/server";
import { getDb, PersonDoc } from "@/lib/mongo";
import { persons as seedPersons } from "@/data/persons";

export async function POST() {
  try {
    const db = await getDb();
    const coll = db.collection<PersonDoc>("persons");

    // Seed with updated structure: name, email, seen, hints.
    // Do NOT set plain codes here; login uses hashedCode generated by the mail script.
    const persons = seedPersons.map((p) => ({
      name: p.name,
      email: p.email,
      seen: p.seen,
      hints: p.hints,
    }));

    for (const p of persons) {
      // Upsert by name (or email). Name is unique in this dataset.
      await coll.updateOne({ name: p.name }, { $set: p }, { upsert: true });
    }

    return NextResponse.json({ inserted: persons.length });
  } catch (e: any) {
    return NextResponse.json({ error: e?.message || "Seed failed" }, { status: 500 });
  }
}
